    <script type="text/javascript" src="resources/default/js/jquery-1.7.1.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery-ui-1.8.17.custom.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.textchange.min.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.alerts.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.form.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.validate.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.metadata.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.uniform.js"></script>
    <script type="text/javascript" src="resources/default/js/autoNumeric-1.7.4.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.pngfix.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.simplemodal.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.livequery.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.datatable/jquery.dataTables.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.datatable/TableTools.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.datatable/ZeroClipboard.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.datatable/jquery.dataTables.columnFilter.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.tipsy.js"></script>
    <script type="text/javascript" src="resources/default/js/jshashtable.js"></script>
    <script type="text/javascript" src="resources/default/js/jquery.numberformatter-1.2.2.js"></script>
    <script type="text/javascript" src="resources/default/js/custom.js"></script>
